### ISSUE TITLE
Terraform >v0.12 Support?

### ISSUE THREAD

**Issue by liamrahav** [palantir/tfjson#13]
Terraform 12 has been out for a month or so now. In v. 12, the format of the output from running `terraform plan` has been changed drastically. Any plans to add support for the new format?

**Comment by mbowen13** [comment]
Why is there a need when Terraform has output to JSON built in in v0.12+?

**Comment by liamrahav** [comment]
@mbowen13 Sorry for not addressing this sooner; I found that out after doing a bit more research. 

For anyone else who come across the same issue, running `terraform plan out=PATH` and then `terraform show -no-color -json PATH` is the workflow to get a JSON version of a plan. The format of the JSON output can be found [here](https://www.terraform.io/docs/internals/json-format.html#plan-representation)
